### ISSUE TITLE
Show qualified statements

### ISSUE THREAD

**Issue by nichtich** [gbv/jskos-proxy#59]
Introduced in JSKOS 0.6.0 and supported by DANTE API.

**Comment by nichtich** [comment]
There is an artificial example (test records) in DANTE dev. Backend needs to be configured to https://dev-api.dante.gbv.de/ to get the record https://officialuri.com/1234_basic:

https://dev-api.dante.gbv.de/data?uri=https://officialuri.com/1234_basic&properties=*&cache=0&format=jskos

See `qualifiedRelations` and `qualifiedLiterals`.

**Comment by rodolv-commons** [comment]
I’ve implemented the display of **Qualified Relations** and **Qualified Literals**, with recursive rendering.

Demo: [https://coli-conc.gbv.de/terminology/cron\_schedule\_expression/?uri=https%3A%2F%2Fofficialuri.com%2F1234\_basic](https://coli-conc.gbv.de/terminology/cron_schedule_expression/?uri=https%3A%2F%2Fofficialuri.com%2F1234_basic)

Given how dense these records are, the current UI struggles to present them clearly.

If qualified statements are typically this rich (many properties and nested objects), we should discuss a more suitable UX pattern and agree on a minimal, improved design for this section.

**Comment by nichtich** [comment]
I think the example record is complex just because it contains every possible kind of data. The layout is ok, some minor improvements possible only.

**Comment by StiftungAusNachlass** [comment]
Thanks!!

The record is extreme; real data is never this long.

I have a few suggestions:

1. No visitor to the site or any of our customers understands "Qualified Statement." It would be nice if we could find a different name for it, or even none at all.
2. It would be great if I could provide a list of hard-coded IRIs and their translations. This would make the view easier to read. For example, "https://w3id.org/dpv/pd#MaritalStatus" would become "Marital status," or "http://schema.org/nationality" would become "Nationality," etc.

Can you include such a translation list?

**Comment by nichtich** [comment]
The translations are also shown *if* the property can be retrieved by jskos-proxy. For instance `http://uri.gbv.de/terminology/ontologic_relation/c6cf731a-47cb-4e8f-a1af-2b9a5de01981` translates to `partOf`.

We should add the following vocabularies anyway:

- schema.org
- GND ontology
- skos ontology
- RDF core
- CIDOC-CRM (only included partial by now)

For the remaining properties and/or meanwhile you might add a vocabulary "Qualified Properties" to DANTE e.g. with

- https://www.wikidata.org/wiki/Property:P102 (should be http://www.wikidata.org/entity/P31 instead)
- https://w3id.org/dpv/pd#MaritalStatus
- http://gov.genealogy.net/ontology.owl#hasDenomination

**Comment by StiftungAusNachlass** [comment]
I will create a DANTE-Vocabulary with the IRI-properties, which are used for the qualified statements.

But first here is the full list of all used IRIs in case Jakob suggests changes. Do you? You f.e. suggested to replace https://www.wikidata.org/wiki/Property:P102 with http://www.wikidata.org/entity/P31 . Isn't P102 much more accurate? It is about a person being member of a political party.


The list does not include URIs, which are a DANTE-URI.

http://www.w3.org/2004/02/skos/core#notation
http://www.w3.org/2008/05/skos-xl#Label
http://www.w3.org/2008/05/skos-xl#prefLabel
http://www.w3.org/2008/05/skos-xl#altLabel
http://www.w3.org/2008/05/skos-xl#hiddenLabel

https://d-nb.info/standards/elementset/gnd#biographicalOrHistoricalInformation
https://d-nb.info/standards/elementset/gnd#academicDegree

https://schema.org/gender
http://schema.org/location
https://schema.org/hasOccupation
https://schema.org/nationality
https://schema.org/relatedTo

https://w3id.org/dpv/pd#MaritalStatus

http://gov.genealogy.net/ontology.owl#hasDenomination

https://www.wikidata.org/wiki/Property:P102

http://www.cidoc-crm.org/cidoc-crm/E5_Event
http://www.cidoc-crm.org/cidoc-crm/P11i_participated_in
http://www.cidoc-crm.org/cidoc-crm/P11_had_participant

https://www.w3.org/1999/02/22-rdf-syntax-ns#type

http://www.w3.org/2004/02/skos/core#Concept
http://www.w3.org/2004/02/skos/core#exactMatch
http://www.w3.org/2004/02/skos/core#scopeNote
http://www.w3.org/2004/02/skos/core#changeNote
http://www.w3.org/2004/02/skos/core#editorialNote
http://www.w3.org/2004/02/skos/core#historyNote
http://www.w3.org/2004/02/skos/core#definition
http://www.w3.org/2004/02/skos/core#example
http://www.w3.org/2004/02/skos/core#note


Should I include the entire list in the vocabulary, or just those you'll continue to lack? And isn't it weird to offer an incomplete list?

**Comment by StiftungAusNachlass** [comment]
I added the records from last comment to a vocabulary in dante:

https://uri.gbv.de/terminology/qualified_properties/
https://api.dante.gbv.de/voc/top?properties=&uri=http:%2F%2Furi.gbv.de%2Fterminology%2Fqualified_properties%2F&cache=0

Please include these. If you add GND-Ontology, schema-org etc, i can delete the dublicate records from dante.

Examplerecord is https://uri.gbv.de/terminology/cron_schedule_expression/?uri=https%3A%2F%2Fofficialuri.com%2F1234_basic

**Comment by StiftungAusNachlass** [comment]
Looking at the example record, I get the feeling that much of what's already there is needed to do the translations. What's the easiest way to determine which of the URIs already exist?

**Comment by StiftungAusNachlass** [comment]
Example: https://uri.gbv.de/terminology/qualified_properties/?uri=http%3A%2F%2Fwww.w3.org%2F2004%2F02%2Fskos%2Fcore%23notation

"http://www.w3.org/2004/02/skos/core#notation" ist not translated yet.

The URI does exist as record, because i added it in the vocabulary "qualified properties": https://uri.gbv.de/terminology/qualified_properties/?uri=http%3A%2F%2Fwww.w3.org%2F2004%2F02%2Fskos%2Fcore%23notation

What's missing for this to be translated?

**Comment by nichtich** [comment]
Fixed in dev: https://coli-conc.gbv.de/terminology/cron_schedule_expression/?uri=https%3A%2F%2Fofficialuri.com%2F1234_basic Some clean-up wanted before release.

**Comment by StiftungAusNachlass** [comment]
Nice! :-)
https://coli-conc.gbv.de/api/data?properties=*&uri=http:%2F%2Fwww.cidoc-crm.org%2Fcidoc-crm%2FP11i_participated_in returns an empty response, although it exists in DANTE: https://api.dante.gbv.de/data?properties=*&uri=http:%2F%2Fwww.cidoc-crm.org%2Fcidoc-crm%2FP11i_participated_in
Can you have a look, why this particular record does not work, while all others do?

Edit: I added https://schema.org/pagination to the qualified-properties-vocabulary, as it was missing.

**Comment by StiftungAusNachlass** [comment]
Same problem as described in last comment with http://www.cidoc-crm.org/cidoc-crm/E5_Event, which is not translated although it exists in DANTE: https://api.dante.gbv.de/data?properties=*&uri=http%3A%2F%2Fwww.cidoc-crm.org%2Fcidoc-crm%2FE5_Event

**Comment by StiftungAusNachlass** [comment]
In example from above the new qualifiedstatements are missing now: https://coli-conc.gbv.de/terminology/cron_schedule_expression/?uri=https%3A%2F%2Fofficialuri.com%2F1234_basic

This is live: https://uri.gbv.de/terminology/language_iso639_1/?uri=http%3A%2F%2Fid.loc.gov%2Fvocabulary%2Fiso639-1%2Fav

We really need some progress here.. 🙏 🙏

**Comment by rodolv-commons** [comment]
Some clarifications about your examples 

**cron_schedule_expression**
- prod shows qualified statements  => https://uri.gbv.de/terminology/cron_schedule_expression/?uri=https%3A%2F%2Fofficialuri.com%2F1234_basic
-  dev does not show  qualified statements => https://coli-conc.gbv.de/terminology/cron_schedule_expression/?uri=https%3A%2F%2Fofficialuri.com%2F1234_basic

**language_iso639_1**
- prod shows qualified statements => https://uri.gbv.de/terminology/language_iso639_1/?uri=http%3A%2F%2Fid.loc.gov%2Fvocabulary%2Fiso639-1%2Fav
- dev does not show qualified statements => https://coli-conc.gbv.de/terminology/language_iso639_1/?uri=http%3A%2F%2Fid.loc.gov%2Fvocabulary%2Fiso639-1%2Fav

So, for both vocs, `development` environment is doing not well but `production` works fine. 

Is that correct for you? 

I will take a look into this discrepancy in development and will give a feedback.

**Comment by rodolv-commons** [comment]
Found and fixed in development; both examples are now working. Please note that production and development  here currently differ quite a lot. I also found some additional issues in development related to recent changes in jskos-vue. I expect to release jskos-vue next week.

**Comment by StiftungAusNachlass** [comment]
NIce, thanks.
An issue is still, that in the presentation of https://coli-conc.gbv.de/terminology/cron_schedule_expression/?uri=https%3A%2F%2Fofficialuri.com%2F1234_basic there is a missing translation for "cidoc-crm.org/cidoc-crm/P11i_participated_in"

This should be translated via https://coli-conc.gbv.de/terminology/qualified_properties/?uri=http%3A%2F%2Fwww.cidoc-crm.org%2Fcidoc-crm%2FP11i_participated_in

Same problem with translation for the record https://uri.gbv.de/terminology/qualified_properties/?uri=http%3A%2F%2Fwww.w3.org%2F2004%2F02%2Fskos%2Fcore%23notation with label "https://www.w3.org/TR/skos-reference/skos-xl.html#prefLabel". Exists here: https://uri.gbv.de/terminology/qualified_properties/?uri=http%3A%2F%2Fwww.w3.org%2F2008%2F05%2Fskos-xl%23prefLabel
